name: pdf_example
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  printing: ^5.11.0
  share_plus: ^12.0.1
  pdf: ^3.11.3
  flutter_svg: ^2.0.17
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0


flutter:

  uses-material-design: true


  assets:
    - assets/fonts/
    - assets/images/


  fonts:
    - family: Lahzeh
      fonts:
        - asset: assets/fonts/Lahzeh-FaNum-Light.ttf
          weight: 300
        - asset: assets/fonts/Lahzeh-FaNum-Regular.ttf
          weight: 400
        - asset: assets/fonts/Lahzeh-FaNum-Medium.ttf
          weight: 500
        - asset: assets/fonts/Lahzeh-FaNum-SemiBold.ttf
          weight: 700
        - asset: assets/fonts/Lahzeh-FaNum-Bold.ttf
          weight: 900

